{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMBQQmPmab67hy09w97FU55",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rileyrahrr-ai/Final-Project-RR/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import yfinance as yf\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "st.title(\"📈 Financial Analysis Dashboard\")\n",
        "\n",
        "st.sidebar.header(\"User Inputs\")\n",
        "\n",
        "# ----- Stock Input -----\n",
        "ticker = st.sidebar.text_input(\"Stock Ticker\", \"AAPL\")\n",
        "\n",
        "# ----- Portfolio Input -----\n",
        "st.sidebar.subheader(\"Portfolio Ticketers\")\n",
        "default = \"AAPL MSFT AMZN GOOG NVDA\"\n",
        "portfolio_input = st.sidebar.text_input(\"Enter 5 tickers (space-separated)\", default)\n",
        "portfolio = portfolio_input.upper().split()\n",
        "\n",
        "# Fixed equal weights for simplicity\n",
        "weights = np.array([1/len(portfolio)] * len(portfolio))\n",
        "\n",
        "# Benchmark\n",
        "benchmark = \"SPY\"\n",
        "\n",
        "st.header(\"Part 1: Individual Stock Analysis\")\n",
        "\n",
        "# Download data\n",
        "data = yf.download(ticker, period=\"6mo\", interval=\"1d\")\n",
        "\n",
        "# Trend analysis\n",
        "data[\"20MA\"] = data[\"Close\"].rolling(20).mean()\n",
        "data[\"50MA\"] = data[\"Close\"].rolling(50).mean()\n",
        "\n",
        "price = data[\"Close\"].iloc[-1]\n",
        "ma20 = data[\"20MA\"].iloc[-1]\n",
        "ma50 = data[\"50MA\"].iloc[-1]\n",
        "\n",
        "if price > ma20 > ma50:\n",
        "    trend = \"Strong Uptrend\"\n",
        "elif price < ma20 < ma50:\n",
        "    trend = \"Strong Downtrend\"\n",
        "else:\n",
        "    trend = \"Mixed Trend\"\n",
        "\n",
        "# RSI\n",
        "delta = data[\"Close\"].diff()\n",
        "gain = delta.clip(lower=0)\n",
        "loss = -delta.clip(upper=0)\n",
        "avg_gain = gain.rolling(14).mean()\n",
        "avg_loss = loss.rolling(14).mean()\n",
        "rs = avg_gain / avg_loss\n",
        "data[\"RSI\"] = 100 - (100 / (1 + rs))\n",
        "\n",
        "rsi_val = data[\"RSI\"].iloc[-1]\n",
        "\n",
        "if rsi_val > 70:\n",
        "    rsi_sig = \"Overbought (Sell Signal)\"\n",
        "elif rsi_val < 30:\n",
        "    rsi_sig = \"Oversold (Buy Signal)\"\n",
        "else:\n",
        "    rsi_sig = \"Neutral\"\n",
        "\n",
        "# Volatility\n",
        "data[\"Return\"] = data[\"Close\"].pct_change()\n",
        "vol = data[\"Return\"].rolling(20).std() * np.sqrt(252)\n",
        "vol_val = vol.iloc[-1]\n",
        "\n",
        "if vol_val > 0.40:\n",
        "    vol_class = \"High\"\n",
        "elif vol_val >= 0.25:\n",
        "    vol_class = \"Medium\"\n",
        "else:\n",
        "    vol_class = \"Low\"\n",
        "\n",
        "# Recommendation\n",
        "if trend == \"Strong Uptrend\" and rsi_sig != \"Overbought (Sell Signal)\":\n",
        "    reco = \"BUY\"\n",
        "elif trend == \"Strong Downtrend\" and rsi_sig != \"Oversold (Buy Signal)\":\n",
        "    reco = \"SELL\"\n",
        "else:\n",
        "    reco = \"HOLD\"\n",
        "\n",
        "# Display\n",
        "st.subheader(f\"Results for {ticker}\")\n",
        "st.write(f\"Trend: {trend}\")\n",
        "st.write(f\"RSI: {rsi_val:.2f} → {rsi_sig}\")\n",
        "st.write(f\"Volatility: {vol_val:.2%} ({vol_class})\")\n",
        "st.write(f\"Recommendation: **{reco}**\")\n",
        "\n",
        "# Plot\n",
        "st.line_chart(data[[\"Close\", \"20MA\", \"50MA\"]])\n",
        "\n",
        "# ---- PART 2 ----\n",
        "st.header(\"Part 2: Portfolio Performance\")\n",
        "\n",
        "prices = yf.download(portfolio, period=\"1y\")[\"Adj Close\"]\n",
        "benchmark_price = yf.download(benchmark, period=\"1y\")[\"Adj Close\"]\n",
        "\n",
        "returns = prices.pct_change().dropna()\n",
        "portfolio_returns = (returns * weights).sum(axis=1)\n",
        "benchmark_returns = benchmark_price.pct_change().dropna()\n",
        "\n",
        "total_return = (1 + portfolio_returns).prod() - 1\n",
        "benchmark_return = (1 + benchmark_returns).prod() - 1\n",
        "outperformance = total_return - benchmark_return\n",
        "vol = portfolio_returns.std() * np.sqrt(252)\n",
        "sharpe = (portfolio_returns.mean() * 252) / (portfolio_returns.std() * np.sqrt(252))\n",
        "\n",
        "# Display\n",
        "st.write(f\"Portfolio Return: {total_return:.2%}\")\n",
        "st.write(f\"SPY Return: {benchmark_return:.2%}\")\n",
        "st.write(f\"Outperformance: {outperformance:.2%}\")\n",
        "st.write(f\"Volatility: {vol:.2%}\")\n",
        "st.write(f\"Sharpe Ratio: {sharpe:.2f}\")\n",
        "\n",
        "# Plot\n",
        "st.line_chart(\n",
        "    pd.DataFrame({\n",
        "        \"Portfolio\": (1 + portfolio_returns).cumprod(),\n",
        "        \"SPY\": (1 + benchmark_returns).cumprod()\n",
        "    })\n",
        ")\n"
      ],
      "metadata": {
        "id": "wnvm0M_lwAzR"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}