{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMkUTDqtbrbbSHBkwdeqbl8",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rileyrahrr-ai/Final-Project-RR/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import yfinance as yf\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "st.set_page_config(page_title=\"Financial Analysis Dashboard\", layout=\"wide\")\n",
        "\n",
        "# =========================================================\n",
        "# Sidebar Inputs\n",
        "# =========================================================\n",
        "st.sidebar.title(\"Settings\")\n",
        "\n",
        "# ----- Stock Input -----\n",
        "st.sidebar.subheader(\"Individual Stock Analysis\")\n",
        "stock_ticker = st.sidebar.text_input(\"Enter Stock Ticker\", \"AAPL\").upper()\n",
        "\n",
        "# ----- Portfolio Input -----\n",
        "st.sidebar.subheader(\"Portfolio Settings\")\n",
        "portfolio_input = st.sidebar.text_input(\n",
        "    \"Enter 5 stock tickers (space-separated)\",\n",
        "    \"AAPL MSFT AMZN GOOG NVDA\"\n",
        ")\n",
        "portfolio_tickers = portfolio_input.upper().split()\n",
        "\n",
        "# Equal weights for simplicity\n",
        "weights = np.array([1/len(portfolio_tickers)] * len(portfolio_tickers))\n",
        "\n",
        "benchmark = \"SPY\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# PART 1: Individual Stock Analysis\n",
        "# =========================================================\n",
        "st.title(\"📈 Financial Analysis Dashboard\")\n",
        "st.header(\"Part 1: Individual Stock Analysis\")\n",
        "\n",
        "try:\n",
        "    data = yf.download(stock_ticker, period=\"6mo\", interval=\"1d\")\n",
        "\n",
        "    # Moving averages\n",
        "    data[\"20MA\"] = data[\"Close\"].rolling(20).mean()\n",
        "    data[\"50MA\"] = data[\"Close\"].rolling(50).mean()\n",
        "\n",
        "    price = data[\"Close\"].iloc[-1]\n",
        "    ma20 = data[\"20MA\"].iloc[-1]\n",
        "    ma50 = data[\"50MA\"].iloc[-1]\n",
        "\n",
        "    # Trend\n",
        "    if price > ma20 > ma50:\n",
        "        trend = \"Strong Uptrend\"\n",
        "    elif price < ma20 < ma50:\n",
        "        trend = \"Strong Downtrend\"\n",
        "    else:\n",
        "        trend = \"Mixed Trend\"\n",
        "\n",
        "    # RSI\n",
        "    delta = data[\"Close\"].diff()\n",
        "    gain = delta.clip(lower=0)\n",
        "    loss = -delta.clip(upper=0)\n",
        "    avg_gain = gain.rolling(14).mean()\n",
        "    avg_loss = loss.rolling(14).mean()\n",
        "    rs = avg_gain / avg_loss\n",
        "    data[\"RSI\"] = 100 - (100 / (1 + rs))\n",
        "    rsi_val = data[\"RSI\"].iloc[-1]\n",
        "\n",
        "    if rsi_val > 70:\n",
        "        rsi_status = \"Overbought (Sell Signal)\"\n",
        "    elif rsi_val < 30:\n",
        "        rsi_status = \"Oversold (Buy Signal)\"\n",
        "    else:\n",
        "        rsi_status = \"Neutral\"\n",
        "\n",
        "    # Volatility\n",
        "    data[\"Return\"] = data[\"Close\"].pct_change()\n",
        "    vol = data[\"Return\"].rolling(20).std() * np.sqrt(252)\n",
        "    vol_val = vol.iloc[-1]\n",
        "\n",
        "    if vol_val > 0.40:\n",
        "        vol_class = \"High\"\n",
        "    elif vol_val >= 0.25:\n",
        "        vol_class = \"Medium\"\n",
        "    else:\n",
        "        vol_class = \"Low\"\n",
        "\n",
        "    # Recommendation\n",
        "    if trend == \"Strong Uptrend\" and rsi_status != \"Overbought (Sell Signal)\":\n",
        "        recommendation = \"BUY\"\n",
        "    elif trend == \"Strong Downtrend\" and rsi_status != \"Oversold (Buy Signal)\":\n",
        "        recommendation = \"SELL\"\n",
        "    else:\n",
        "        recommendation = \"HOLD\"\n",
        "\n",
        "    # Display results\n",
        "    st.subheader(f\"Results for {stock_ticker}\")\n",
        "    st.write(f\"**Trend:** {trend}\")\n",
        "    st.write(f\"**RSI:** {rsi_val:.2f} → {rsi_status}\")\n",
        "    st.write(f\"**Volatility:** {vol_val:.2%} ({vol_class})\")\n",
        "    st.write(f\"### Final Recommendation: **{recommendation}**\")\n",
        "\n",
        "    # Plot\n",
        "    st.subheader(\"Trend Chart\")\n",
        "    st.line_chart(data[[\"Close\", \"20MA\", \"50MA\"]])\n",
        "\n",
        "except Exception as e:\n",
        "    st.error(\"Error loading stock data. Please check the ticker and try again.\")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# PART 2: Portfolio Performance Dashboard\n",
        "# =========================================================\n",
        "st.header(\"Part 2: Portfolio Performance\")\n",
        "\n",
        "try:\n",
        "    # Download data\n",
        "    prices = yf.download(portfolio_tickers, period=\"1y\")[\"Adj Close\"]\n",
        "    benchmark_price = yf.download(benchmark, period=\"1y\")[\"Adj Close\"]\n",
        "\n",
        "    # Returns\n",
        "    returns = prices.pct_change().dropna()\n",
        "    portfolio_returns = (returns * weights).sum(axis=1)\n",
        "    benchmark_returns = benchmark_price.pct_change().dropna()\n",
        "\n",
        "    # Metrics\n",
        "    total_return = (1 + portfolio_returns).prod() - 1\n",
        "    benchmark_return = (1 + benchmark_returns).prod() - 1\n",
        "    outperformance = total_return - benchmark_return\n",
        "\n",
        "    vol = portfolio_returns.std() * np.sqrt(252)\n",
        "    sharpe = (portfolio_returns.mean() * 252) / (portfolio_returns.std() * np.sqrt(252))\n",
        "\n",
        "    # Display results\n",
        "    st.subheader(\"Portfolio Metrics\")\n",
        "    st.write(f\"**Portfolio Total Return:** {total_return:.2%}\")\n",
        "    st.write(f\"**SPY Benchmark Return:** {benchmark_return:.2%}\")\n",
        "    st.write(f\"**Outperformance:** {outperformance:.2%}\")\n",
        "    st.write(f\"**Annualized Volatility:** {vol:.2%}\")\n",
        "    st.write(f\"**Sharpe Ratio:** {sharpe:.2f}\")\n",
        "\n",
        "    # Plot comparison\n",
        "    st.subheader(\"Cumulative Return Comparison\")\n",
        "    cum_returns = pd.DataFrame({\n",
        "        \"Portfolio\": (1 + portfolio_returns).cumprod(),\n",
        "        \"SPY\": (1 + benchmark_returns).cumprod()\n",
        "    })\n",
        "    st.line_chart(cum_returns)\n",
        "\n",
        "except Exception as e:\n",
        "    st.error(\"Error loading portfolio data. Please check the tickers.\")\n"
      ],
      "metadata": {
        "id": "wnvm0M_lwAzR"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}